/**
 * 平台配置文件
 * 定义不同CTF平台的特定配置和选择器
 */

const PLATFORM_CONFIGS = {
    'nssctf.cn': {
        name: 'NSSCTF',
        titleProcessor: (title) => {
            // NSSCTF特定的标题处理逻辑
            title = title.split('|')[0].trim();
            title = title.replace(/[?|:<>"*\/\\]/g, '');

            const bracketRegex = /\[([^\]]+)\]/g;
            const bracketContents = [];
            let match;

            while ((match = bracketRegex.exec(title)) !== null) {
                bracketContents.push(match[1].trim());
            }

            const problemName = title.split(']').pop().trim();
            let formattedTitle = bracketContents.join('-');

            if (problemName && problemName !== formattedTitle) {
                formattedTitle = formattedTitle ? `${formattedTitle}-${problemName}` : problemName;
            }

            return formattedTitle.replace(/[-\s]+/g, '-').replace(/^-+|-+$/g, '') || 'Unknown';
        }
    },

    'ctf.show': {
        name: 'CTF Show',
        titleProcessor: (title) => {
            // CTF Show特定的标题处理逻辑
            title = title.replace(/CTF Show/gi, '').trim();
            title = title.replace(/[?|:<>"*\/\\]/g, '');
            return title.replace(/[-\s]+/g, '-').replace(/^-+|-+$/g, '') || 'Unknown';
        }
    },

    'buuoj.cn': {
        name: 'BUUOJ',
        titleProcessor: (title) => {
            // BUUOJ特定的标题处理逻辑
            title = title.replace(/BUUOJ/gi, '').trim();
            title = title.replace(/[?|:<>"*\/\\]/g, '');
            return title.replace(/[-\s]+/g, '-').replace(/^-+|-+$/g, '') || 'Unknown';
        }
    }
};

/**
 * 默认模板配置
 */
const DEFAULT_TEMPLATES = {
    standard: {
        name: '标准模板',
        content: `## 基本信息
- **题目名称**：{{title}}
- **题目链接**：{{url}}
- **创建时间**：{{date}} {{time}}
- **考点清单**：

## 解题思路


## 过程和结果记录


## 总结


## 相关知识点


---
*Generated by Obsidian WriteUp Helper*`
    },
    
    detailed: {
        name: '详细模板',
        content: `# {{title}}

## 📋 基本信息
| 项目 | 内容 |
|------|------|
| 题目名称 | {{title}} |
| 题目链接 | {{url}} |
| 创建时间 | {{date}} {{time}} |

## 🎯 考点清单
- [ ]

## 💡 解题思路


## 📝 过程和结果记录


## 🔍 详细分析


## 📚 相关知识点


## 🎉 总结


## 🔗 参考资料


---
*Generated by Obsidian WriteUp Helper v2.0*`
    },
    
    simple: {
        name: '简洁模板',
        content: `# {{title}}

**链接**: {{url}}
**时间**: {{date}}

## 思路


## 过程


## 总结

`
    }
};

/**
 * 获取当前平台配置
 * @returns {Object} 平台配置对象
 */
function getCurrentPlatformConfig() {
    try {
        if (typeof window === 'undefined' || !window.location) {
            console.warn('WriteUp Helper: 无法获取window.location，使用默认配置');
            return PLATFORM_CONFIGS['nssctf.cn'];
        }

        const hostname = window.location.hostname;

        for (const [domain, config] of Object.entries(PLATFORM_CONFIGS)) {
            if (hostname.includes(domain)) {
                return config;
            }
        }

        // 返回默认配置
        return PLATFORM_CONFIGS['nssctf.cn'];
    } catch (error) {
        console.error('WriteUp Helper: 获取平台配置失败', error);
        return PLATFORM_CONFIGS['nssctf.cn'];
    }
}

/**
 * 导出配置
 */
if (typeof module !== 'undefined' && module.exports) {
    module.exports = {
        PLATFORM_CONFIGS,
        DEFAULT_TEMPLATES,
        getCurrentPlatformConfig
    };
}
